# Generated by Django 5.0.4 on 2024-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Run', 'Run'), ('Ride', 'Ride'), ('Swim', 'Swim'), ('Walk', 'Walk'), ('Gym', 'Gym'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=50)),
                ('time', models.TimeField()),
                ('distance', models.IntegerField()),
                ('elevationgain', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
