# Generated by Django 5.0.4 on 2024-04-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_activity_type_alter_sleep_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='mood',
            field=models.CharField(max_length=25),
        ),
    ]
