# Generated by Django 5.0.4 on 2024-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_activity_calories_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default='N/A', max_length=75),
        ),
    ]
