# Generated by Django 5.0.4 on 2024-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_nutrition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Date (yyyy/mm/dd)'),
        ),
    ]
