# Generated by Django 5.0.4 on 2024-04-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_activity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='Activity',
            new_name='activity',
        ),
    ]
