# Generated by Django 5.0.4 on 2024-04-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_activity_user_sleep_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Date (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(verbose_name='Date (yyyy-mm-dd)'),
        ),
    ]
